// <auto-generated />
namespace test32.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Ccccc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ccccc));
        
        string IMigrationMetadata.Id
        {
            get { return "202307150956378_Ccccc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
